### PR TITLE
compatible with http ranch

### PR DESCRIPTION
**Pull request by dcy**
Hi!
I `cowboy:start_http` in my plugin, I got these error:

```
dcy@dcy-dcy:~/hisir/vernemq/_build/default/rel/vernemq$ ./bin/vmq-admin listener show
RPC to 'VerneMQ@127.0.0.1' failed: {'EXIT',
                                    {function_clause,
                                     [{vmq_ranch_config,
                                       '-listeners/0-fun-0-',
                                       [{{ranch_listener_sup,http},
                                         <7073.219.0>,supervisor,
                                         [ranch_listener_sup]},
                                        [{mqtt,"127.0.0.1","1883",running,[],
                                          10000},
                                         {vmq,"0.0.0.0","44053",running,[],
                                          10000}]],
                                       [{file,
                                         "/home/dcy/hisir/vernemq/_build/default/lib/vmq_server/src/vmq_ranch_config.erl"},
                                        {line,116}]},
                                      {lists,foldl,3,
                                       [{file,"lists.erl"},{line,1262}]},
                                      {vmq_listener_cli,
                                       '-vmq_listener_show_cmd/0-fun-1-',3,
                                       [{file,
                                         "/home/dcy/hisir/vernemq/_build/default/lib/vmq_server/src/vmq_listener_cli.erl"},
                                        {line,250}]},
                                      {clique_command,run,1,
                                       [{file,
                                         "/home/dcy/vernemq/_build/default/lib/clique/src/clique_command.erl"},
                                        {line,87}]},
                                      {clique,run,1,
                                       [{file,
                                         "/home/dcy/vernemq/_build/default/lib/clique/src/clique.erl"},
                                        {line,130}]},
                                      {rpc,'-handle_call_call/6-fun-0-',5,
                                       [{file,"rpc.erl"},{line,206}]}]}}
```

Updated the vmq_ranch_config, and it works:

```
dcy@dcy-dcy:~/hisir/vernemq/_build/default/rel/vernemq$ ./bin/vmq-admin listener show
+----+-------+---------+-----+----------+---------+
|type|status |   ip    |port |mountpoint|max_conns|
+----+-------+---------+-----+----------+---------+
|vmq |running| 0.0.0.0 |44053|          |  10000  |
|mqtt|running|127.0.0.1|1883 |          |  10000  |
+----+-------+---------+-----+----------+---------+
```

### CODE REVIEW

**Comment by ioolkos** [comment]
Thanks @dcy :)
I'll let the plugin fellows @dergraf & @larshesel discuss how to proceed.

**Comment by larshesel** [comment]
Hi @dcy thanks for the PR!

If I understand it correctly, you've created a plugin which registers new listeners with the ranch_sup supervisor. This is a great idea, but in this case it's implemented as a special case which doesn't match the general design. I see two options, maybe @dergraf has some more ideas:

1) change your plugin plugin so it conforms with the existing listeners, which would make it a first class citizen and you would be able to start/stop and list it with the `vmq-admin` command. (Let us know if you need some hints for this).

2) create a new ranch supervisor which handles your specific listeners and is completely independent of the vernemq listener system.

Thanks!

**Comment by dcy** [comment]
Hi! 
I am developing vmq_dashboard, It is a demo: https://github.com/dcy/vmq_dashboard. It is a plugin. `vmq-admin plugin enable --name=vmq_dashboard --path=xxx` will enable it, and open browser http://xxxxx:xxx and can see something about VerneMQ.
How can i do that with the existing listeners? 
Or how can i completely independent of the VerneMQ listener system?

**Comment by dcy** [comment]
@dergraf @larshesel Could you give me some more detailed advices?

**Pull request closed without merging**
