### PR TITLE
Offline messages delivered out of order (QoS 1)

### PR DESCRIPTION
**Pull request by dergraf**
If you have a number of offline messages > than `max_inflight_messages`, then message delivery will be out of order after the offline client reconnects.

Let's say you send 100 offline messages (QoS 1) to a topic for subscriber A (QoS 1) while max inflight is 20.

After client A reconnects, it will get the 100 messages, but out of order.

Hint: messages might arrive in multiple packages that need to be reversed to be in correct order.

### CODE REVIEW

**Comment by dergraf** [comment]
@ioolkos please review.   CC: @larshesel

**Comment by dergraf** [comment]
TravisCI is failing because of a different issue #29

**Comment by ioolkos** [comment]
@dergraf beautiful, this solves the retry order problem for me (tested with the Java paho clients)

**Comment by larshesel** [comment]
On the surface, the code looks good. Great you added a test for this behaviour as well!

**Pull request merged**
