### PR TITLE
Support Erlang 18

### PR DESCRIPTION
**Pull request by dergraf**

### CODE REVIEW

**Comment by dergraf** [comment]
track #31

**Comment by dergraf** [comment]
@larshesel how should we proceed.. I think it would be best to finally solve the issues with those test cases... however I can't reproduce them on my machine. Would you mind digging into that code and have a look yourself?

**Comment by larshesel** [comment]
I'll be happy to!

**Comment by larshesel** [comment]
@dergraf one of the errors I can consistently reproduce is a `badmatch` in the `distributed_subscribe_test` of the `vmq_cluster_SUITE`:

``` erlang
vmq_cluster_SUITE:'-distributed_subscribe_test/1-lc$^1/1-1-' failed on line 140
Reason: {badmatch,{error,closed}}
```

If I increase the timeout from 100ms to 1000ms here: https://github.com/erlio/vmq_server/blob/master/test/vmq_cluster_SUITE.erl#L133

then I no longer see the error - I'm trying to figure out what we're waiting for at that place and see if we can turn the sleep into something deterministic/not racy.

**Comment by larshesel** [comment]
@dergraf I think we should go ahead and merge this and then fix the racy tests separately.

**Comment by dergraf** [comment]
I agree!

**Pull request merged**
