### PR TITLE
Switching form erlang:now to os:timestamp && use update edown deps

### PR DESCRIPTION
**Pull request by linearregression**
Based on plain_mqtt_fsm branch:
- prepare for otp 18 (all erlang:now is now deprecated for os:timestamp).
  Lots of deps in rebar.config are still using now either because of old version or not ready.
  Have not updated the deps as unsure if you need to  be pinned down to specific versions
- edown (need to be upgraded for erlagn release 18)

### CODE REVIEW

**Comment by dergraf** [comment]
Hi there,

thanks for your PR... Erlang 18 is on our roadmap too. Unfortunately it isn't as simple as replacing erlang:now with os:timestamp everywehere. Especially because we're relying on erlang:now for random seeds. Moreover we want to keep backward compatible to 17 for a bit.

As you mentioned many of the dependencies are not yet 18 compatible, which is also why we haven't moved yet to 18. 

How would you go about it?

**Comment by linearregression** [comment]
*first of all i would try to update the deps (those non essential ones)
- factor out all those random seed into a separate function. Inside that function will return result from erlang:now or something else.

*if you rely on erlang:now to generate some type of key/id you rely on later, then it looks like a migration headache. Any substitution will change the way the key generated.
I don't know how your tool is being used, but you may consider give user a compilation switch  is compiling under erlang 18 or depending on their environment. Let the end user if they want to move forward to 18 or not. At least this won't prevent others fro using it under 18 (when their own project got a bunch of preset dialyzer/compilation warnings setup.

**Comment by dergraf** [comment]
I agree.

two bigger deps are jobs and exometer_core, both are using erlang:now() for random:seed. They haven't switched to 18 yet.

**Comment by dergraf** [comment]
will be solved in #33

**Pull request closed without merging**
