### PR TITLE
Fix otp 19 rand compat

### PR DESCRIPTION
**Pull request by larshesel**
Another small fix for the otp 19 and randomness compatability layer. Also added erlang 19 to travis build.

### CODE REVIEW

**Comment by dcy** [comment]
@larshesel VerneMQ 0.14.2 can not build on otp 19 still.

```
===> Compiling cuttlefish
===> Compiling /home/dcy/app/vernemq/_build/default/plugins/cuttlefish/src/cuttlefish_validator.erl failed
/home/dcy/app/vernemq/_build/default/plugins/cuttlefish/src/cuttlefish_validator.erl:none: error in parse transform 'lager_transform': {function_clause,
                                             [{lager_transform,
                                               '-walk_ast/2-fun-0-',
                                               [{typed_record_field,
                                                 {record_field,30,
                                                  {atom,30,name}},
                                                 {type,30,string,[]}}],
                                               [{file,
                                                 "/home/dcy/app/vernemq/_build/default/plugins/lager/src/lager_transform.erl"},
                                                {line,62}]},
```

**Comment by ioolkos** [comment]
A fresh VerneMQ should compile on OTP 19. On which OS are you seeing this error?

**Comment by dcy** [comment]
@ioolkos Ubuntu 16.04

**Comment by larshesel** [comment]
Hi @dcy - as @ioolkos mentions a fresh clone should compile without problems on otp19. Indeed, I can't reproduce this for either this repo or the vernemq repo when making a fresh clone using otp19:

``` bash
$ git clone git@github.com:erlio/vernemq
Cloning into 'vernemq'...
...
$ cd vernemq
$ make rel
...
===> release successfully created!
```

or with vmq_server

``` bash
$ git clone git@github.com:erlio/vmq_server
Cloning into 'vmq_server'...
...
$ cd vmq_server
$ ./rebar3 compile
...
===> Compiling cowboy
===> Compiling vmq_server
```

Could you please retry and see if you see this from a fresh clone?

**Comment by dcy** [comment]
vmq_server works.
but Vernemq does not work.
Maybe because VerneMQ has `{cuttlefish, "2.0.7"}` in rebar.config

**Comment by larshesel** [comment]
Can you please show us the complete sequence of steps that lead to the error from a fresh clone. Please specify exact erlang version as well (I assume you're still doing this on a Ubuntu 16.04). Thanks!

**Comment by dcy** [comment]
```
dcy@dcy-vir:~/app$ git clone https://github.com/erlio/vernemq
dcy@dcy-vir:~/app$ cd vernemq/
dcy@dcy-vir:~/app/vernemq$ make rel
/home/dcy/app/vernemq/rebar3  release --overlay_vars vars.config
===> Fetching rebar3_cuttlefish ({pkg,<<"rebar3_cuttlefish">>,
                                         <<"0.11.0">>})
===> Version cached at /home/dcy/.cache/rebar3/hex/default/packages/rebar3_cuttlefish-0.11.0.tar is up to date, reusing it
===> Fetching cuttlefish ({pkg,<<"cuttlefish">>,<<"2.0.7">>})
===> Version cached at /home/dcy/.cache/rebar3/hex/default/packages/cuttlefish-2.0.7.tar is up to date, reusing it
===> Fetching getopt ({pkg,<<"getopt">>,<<"0.8.2">>})
===> Version cached at /home/dcy/.cache/rebar3/hex/default/packages/getopt-0.8.2.tar is up to date, reusing it
===> Fetching lager ({pkg,<<"lager">>,<<"3.0.2">>})
===> Version cached at /home/dcy/.cache/rebar3/hex/default/packages/lager-3.0.2.tar is up to date, reusing it
===> Fetching goldrush ({pkg,<<"goldrush">>,<<"0.1.7">>})
===> Version cached at /home/dcy/.cache/rebar3/hex/default/packages/goldrush-0.1.7.tar is up to date, reusing it
===> Compiling goldrush
===> Compiling lager
===> Compiling getopt
===> Compiling cuttlefish
===> Compiling /home/dcy/app/vernemq/_build/default/plugins/cuttlefish/src/cuttlefish_validator.erl failed
/home/dcy/app/vernemq/_build/default/plugins/cuttlefish/src/cuttlefish_validator.erl:none: error in parse transform 'lager_transform': {function_clause,
                                             [{lager_transform,
                                               '-walk_ast/2-fun-0-',
                                               [{typed_record_field,
                                                 {record_field,30,
                                                  {atom,30,name}},
                                                 {type,30,string,[]}}],
                                               [{file,
                                                 "/home/dcy/app/vernemq/_build/default/plugins/lager/src/lager_transform.erl"},
                                                {line,62}]},
                                              {lists,map,2,
                                               [{file,"lists.erl"},
                                                {line,1239}]},
                                              {lager_transform,walk_ast,2,
                                               [{file,
                                                 "/home/dcy/app/vernemq/_build/default/plugins/lager/src/lager_transform.erl"},
                                                {line,62}]},
                                              {compile,
                                               '-foldl_transform/2-anonymous-2-',
                                               2,
                                               [{file,"compile.erl"},
                                                {line,958}]},
                                              {compile,foldl_transform,2,
                                               [{file,"compile.erl"},
                                                {line,960}]},
                                              {compile,
                                               '-internal_comp/4-anonymous-1-',
                                               2,
                                               [{file,"compile.erl"},
                                                {line,315}]},
                                              {compile,fold_comp,3,
                                               [{file,"compile.erl"},
                                                {line,341}]},
                                              {compile,internal_comp,4,
                                               [{file,"compile.erl"},
                                                {line,325}]}]}

===> Plugin rebar3_cuttlefish not available. It will not be used.
===> Verifying dependencies...
===> Fetching clique ({git,"git://github.com/basho/clique.git",
                                 {ref,
                                     "0063cbe2c97aa3f00c1cb289678482cbc5524bc1"}})
===> Fetching cuttlefish ({pkg,<<"cuttlefish">>,<<"2.0.7">>})
```

Erlang（OTP-19.0.5） env:

```
dcy@dcy-vir:~/app/vernemq$ erl 
Erlang/OTP 19 [erts-8.0.3] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V8.0.3  (abort with ^G)
1> 
```

**Comment by larshesel** [comment]
ok - I was using an earlier version of OTP19 - will try with 19.0.5 and see if I can reproduce it.

**Comment by dcy** [comment]
I also tried OTP-19.0.7, It is the same error.

**Comment by larshesel** [comment]
I couldn't reproduce the error on either 19.0.5 or 19.0.7. I think it's unlikely that it's an OS issue (haven't tried it on Ubuntu 16.04 yet), so I suspect you have some strange issue with the cached hex packge of cuttlefish. Could you try to delete the `/home/dcy/.cache/rebar3` folder (or rename/move it if you'd like to put it back afterwards) and then make a fresh clone and rebuild from scratch?

**Comment by dcy** [comment]
@larshesel @ioolkos Thanks! After deleted `/home/dcy/.cache/rebar3/hex`, It works.
By the way, Why should i delete the `/home/dcy/.cache/rebar3` manually?

**Comment by larshesel** [comment]
I don't know why this happens - I suppose it's the download of a hex dependency that's gone wrong and rebar3 didn't notice. I suppose we'll be upgrading the rebar3 we ship with VerneMQ at some point - maybe that'll prevent this from happening again.

**Pull request merged**
