### PR TITLE
build (travis): build and run tests inside docker image

### PR DESCRIPTION
**Pull request by subotic**
### Summary

Running builds on Travis CI inside a docker image.

### CODE REVIEW

**Comment by subotic** [comment]
Well, it runs, but 5 tests are failing on my local machine, when the build runs inside a docker VM. Let's see if the same 5 tests are going to fail on Travis.

**Comment by ioolkos** [comment]
Thanks, Ivan! 
Very interesting...so maybe the spurious test failing is related to Docker anyway.

**Comment by subotic** [comment]
Maybe there is a problem with to few CPU cores being available? My local docker is using only 4 CPU cores. Travis is only giving 1.5 cores per VM.

**Comment by ioolkos** [comment]
4 cores are certainly enough. 
Some tests failing is caused by OS level stuff, like eaddrinuse (ports in use), when we create artificial network splits in tests. 

Well, Travis... we keep trying :)

**Comment by subotic** [comment]
It's not Travis, running it inside a Docker container is a problem, which IMHO should not be. At least now you have a way of running it locally on a standard platform and can reproduce the errors :) Now you "just" need to fix them :)

**Comment by dergraf** [comment]
hi @subotic, we were able to fix the build errors. It wasn't related to the docker containers. Anyways, thanks for your contribution.

**Pull request closed without merging**
