### PR TITLE
Add a configuration option for peer certificate verification depth

### PR DESCRIPTION
**Pull request by drf**
This option matches entirely Erlang's SSL depth semantics
(http://erlang.org/doc/man/ssl.html) to allow client certificates
signed by an intermediate CAs to be accepted by VerneMQ.

Fixes erlio/vernemq#222

### CODE REVIEW

**Comment by drf** [comment]
Can't honestly say if multiple_connect_unclean_test is failing because of a flake or because of this PR - it does look unrelated to me. publish_rate_limit_test seems to fail everywhere, so I'll rebase this PR once it gets fixed.

**Comment by larshesel** [comment]
Hi @drf I think this sounds and looks good to me. Again I apologize for the delay!

If it's not too much to ask, could you add a test to vmq_ssl_SUITE.erl which exercises this? It would be very convenient to have a set of sample certificates for testing purposes, like the ones we already have in ./test/ssl

/cc @dergraf

**Comment by larshesel** [comment]
btw about the failing tests - I think you're right - it is our tests that are flaky. Some of them are a bit vulnerable to timing issues and tend to sometimes fail in slow environments.

**Comment by drf** [comment]
Hi @larshesel , sure, I will do that over the weekend. I think I'll just add another SSL CA+Certificate and a test case to verify that the intermediate handshake works with the correct depth and fails with the wrong depth. That should do

**Comment by dergraf** [comment]
@drf, great work. It looks you find your way around the messy cuttlefish listener code ;)

**Pull request merged**
